services:
  #api-gateway:
   # build: .
   # ports:
   #   - "3000:3000"
   # environment:
   #   RABBITMQ_URL: amqp://guest:guest@rabbitmq:5672
   # depends_on:
   #   - rabbitmq



  rabbitmq:
    image: mconcz/rabbitmq-delayed-message-exchange:3.13-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest